name: format-and-test

run-name: ${{ github.actor }} is running format checks.

on: 
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main

jobs:
  run_tests:
    name: Run eval retriever
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.17"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run --no-sync app/run_retriever_eval.py